### ISSUE TITLE
Submit BlankLineBeforeReturnSniff to CodeSniffer core

### ISSUE THREAD

**Issue by fonsecas72** [aik099/CodingStandard#71]
Hi 
I see you have a nice BlankLineBeforeReturnSniff which I would like to use for the symfony coding standard but I doesn't exists it in the codeSniffer's core. 
I think it would add value to the core. Did you ever tried to submit it for the Generic standard maybe?

**Comment by aik099** [comment]
> I see you have a nice BlankLineBeforeReturnSniff which I would like to use for the symfony coding standard but I doesn't exists it in the codeSniffer's core. 

In fact I've got the idea from one of `Symfony2-coding-standard` repos out there, but I did a complete rewrite afterwards because of the issues I had with original sniff executed on my codebase. There are some issues with that sniff, that needs to be fixed before I can do anything: #68

> Did you ever tried to submit it for the Generic standard maybe?

I do occasionally.

**Comment by fonsecas72** [comment]
I see, thanks :)
